"""Fix: Cambio de nombre de la variable page_id por pages_id en la tabla verb para mantener consistencia

Revision ID: f5ced6ce15fb
Revises: ddc1854ac26f
Create Date: 2026-05-18 10:56:38.294894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ced6ce15fb'
down_revision: Union[str, Sequence[str], None] = 'ddc1854ac26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('pages_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('countries_pages_iD_fkey'), 'countries', type_='foreignkey')
    op.create_foreign_key(None, 'countries', 'pages', ['pages_id'], ['id'])
    op.drop_column('countries', 'pages_iD')
    op.add_column('verbs', sa.Column('pages_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('verbs_page_id_fkey'), 'verbs', type_='foreignkey')
    op.create_foreign_key(None, 'verbs', 'pages', ['pages_id'], ['id'])
    op.drop_column('verbs', 'page_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verbs', sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'verbs', type_='foreignkey')
    op.create_foreign_key(op.f('verbs_page_id_fkey'), 'verbs', 'pages', ['page_id'], ['id'])
    op.drop_column('verbs', 'pages_id')
    op.add_column('countries', sa.Column('pages_iD', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'countries', type_='foreignkey')
    op.create_foreign_key(op.f('countries_pages_iD_fkey'), 'countries', 'pages', ['pages_iD'], ['id'])
    op.drop_column('countries', 'pages_id')
    # ### end Alembic commands ###
